services:
  mysql:
    image: mysql:9.2.0
    container_name: MySQL_ShopApp
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ShopApp
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
